# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json

root: true
env:
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - import
  - unused-imports
rules:
  '@typescript-eslint/no-unused-vars': off
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: '^_'
      args: after-used
      argsIgnorePattern: '^_'
  import/order:
    - error
    - groups:
        - builtin
        - external
        - parent
        - sibling
        - index
        - type
      alphabetize:
        order: asc
      newlines-between: always
